server:
  port: 11221
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
       - id: account
         uri: lb://account
         predicates:
          - Path=/account/**
         filters:
          - StripPrefix=1
       - id: logger
         uri: lb://logger
         predicates:
           - Path=/logger/**
         filters:
           - StripPrefix=1
eureka:
  instance:
    hostname: localhost
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://localhost:11220/eureka/

logging:
#  config: classpath:logback-spring.xml
  path: /Users/pwd/Desktop/logger
