server:
  port: 11221
spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
  zipkin:
    base-url: http://localhost:11250/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  instance:
    hostname: localhost
    status-page-url: http://localhost:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:11220/eureka/
    enabled: true

logging:
#  config: classpath:logback-spring.xml
#  path: /Users/pwd/Desktop/logger
  level:
    org.springframework.cloud.gateway: debug

account_login_prefix: sso_identify_
filter_skip_all: false
