package pwd.initializr.typeface.persistence.dao;

import pwd.initializr.typeface.persistence.entity.FontEntity;

public interface FontEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table font
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table font
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int insert(FontEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table font
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int insertSelective(FontEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table font
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    FontEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table font
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int updateByPrimaryKeySelective(FontEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table font
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int updateByPrimaryKey(FontEntity record);
}