package pwd.initializr.typeface.persistence.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pwd.initializr.typeface.persistence.entity.PaintingEntity;
import pwd.initializr.typeface.persistence.entity.PaintingEntityExample;

public interface PaintingEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int countByExample(PaintingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int deleteByExample(PaintingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int insert(PaintingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int insertSelective(PaintingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    List<PaintingEntity> selectByExample(PaintingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    PaintingEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaintingEntity record, @Param("example") PaintingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int updateByExample(@Param("record") PaintingEntity record, @Param("example") PaintingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int updateByPrimaryKeySelective(PaintingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    int updateByPrimaryKey(PaintingEntity record);
}