server.port=${projectPort}
spring.application.name=${projectName}
#################logger######################
logging.level.root=INFO
logging.path=./z-log/${spring.application.name}
################thymeleaf####################
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=utf-8
#################zipkin######################
spring.zipkin.enabled=false
spring.zipkin.base-url=http://localhost:12040
spring.zipkin.sender.type=web
spring.sleuth.sampler.probability=1.0
#################eureka######################
eureka.client.enabled=false
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
eureka.instance.status-page-url=http://localhost:${server.port}/swagger-ui.html
################datasource####################
spring.datasource.name=${databaseName}
spring.datasource.url=${databaseUrl}
spring.datasource.username=${databaseUser}
spring.datasource.password=${databasePwd}
spring.datasource.driver-class-name=${databaseDriver}
##################druid#######################
spring.datasource.druid.initial-size=5
spring.datasource.druid.min-idle=5
spring.datasource.druid.max-active=20
spring.datasource.druid.max-wait=60000
spring.datasource.druid.test-while-idle=true
spring.datasource.druid.time-between-eviction-runs-millis=60000
spring.datasource.druid.min-evictable-idle-time-millis=30000
# mysql:select 'x'
# oracle:select 1 from dual
spring.datasource.druid.validation-query=select 'x'
spring.datasource.druid.test-on-borrow=false
spring.datasource.druid.test-on-return=false
spring.datasource.druid.max-pool-prepared-statement-per-connection-size=20
spring.datasource.druid.filters=stat,wall
spring.datasource.druid.connection-properties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
spring.datasource.druid.use-global-data-source-stat=true
spring.datasource.druid.stat-view-servlet.login-username=root
spring.datasource.druid.stat-view-servlet.login-password=root
