package pwd.initializr.typeface.persistence.entity;

public class FontEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column font.id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column font.title
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column font.name
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column font.file_url
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private String file_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column font.thumb_url
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private String thumb_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column font.status
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column font.create_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Long create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column font.update_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column font.id
     *
     * @return the value of font.id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column font.id
     *
     * @param id the value for font.id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column font.title
     *
     * @return the value of font.title
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column font.title
     *
     * @param title the value for font.title
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column font.name
     *
     * @return the value of font.name
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column font.name
     *
     * @param name the value for font.name
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column font.file_url
     *
     * @return the value of font.file_url
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getFile_url() {
        return file_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column font.file_url
     *
     * @param file_url the value for font.file_url
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setFile_url(String file_url) {
        this.file_url = file_url == null ? null : file_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column font.thumb_url
     *
     * @return the value of font.thumb_url
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getThumb_url() {
        return thumb_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column font.thumb_url
     *
     * @param thumb_url the value for font.thumb_url
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setThumb_url(String thumb_url) {
        this.thumb_url = thumb_url == null ? null : thumb_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column font.status
     *
     * @return the value of font.status
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column font.status
     *
     * @param status the value for font.status
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column font.create_time
     *
     * @return the value of font.create_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column font.create_time
     *
     * @param create_time the value for font.create_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column font.update_time
     *
     * @return the value of font.update_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column font.update_time
     *
     * @param update_time the value for font.update_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}