package pwd.initializr.typeface.persistence.entity;

public class PaintingEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.user_id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.font_id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Long font_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.font_size
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Float font_size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.content
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.background
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private String background;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.foreground
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private String foreground;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.width
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.height
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.image_url
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private String image_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.bucket_name
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private String bucket_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.object_name
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private String object_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.status
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.create_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Long create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column painting.update_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.id
     *
     * @return the value of painting.id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.id
     *
     * @param id the value for painting.id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.user_id
     *
     * @return the value of painting.user_id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.user_id
     *
     * @param user_id the value for painting.user_id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.font_id
     *
     * @return the value of painting.font_id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Long getFont_id() {
        return font_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.font_id
     *
     * @param font_id the value for painting.font_id
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setFont_id(Long font_id) {
        this.font_id = font_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.font_size
     *
     * @return the value of painting.font_size
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Float getFont_size() {
        return font_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.font_size
     *
     * @param font_size the value for painting.font_size
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setFont_size(Float font_size) {
        this.font_size = font_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.content
     *
     * @return the value of painting.content
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.content
     *
     * @param content the value for painting.content
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.background
     *
     * @return the value of painting.background
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getBackground() {
        return background;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.background
     *
     * @param background the value for painting.background
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setBackground(String background) {
        this.background = background == null ? null : background.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.foreground
     *
     * @return the value of painting.foreground
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getForeground() {
        return foreground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.foreground
     *
     * @param foreground the value for painting.foreground
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setForeground(String foreground) {
        this.foreground = foreground == null ? null : foreground.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.width
     *
     * @return the value of painting.width
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.width
     *
     * @param width the value for painting.width
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.height
     *
     * @return the value of painting.height
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.height
     *
     * @param height the value for painting.height
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.image_url
     *
     * @return the value of painting.image_url
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getImage_url() {
        return image_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.image_url
     *
     * @param image_url the value for painting.image_url
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setImage_url(String image_url) {
        this.image_url = image_url == null ? null : image_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.bucket_name
     *
     * @return the value of painting.bucket_name
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getBucket_name() {
        return bucket_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.bucket_name
     *
     * @param bucket_name the value for painting.bucket_name
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setBucket_name(String bucket_name) {
        this.bucket_name = bucket_name == null ? null : bucket_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.object_name
     *
     * @return the value of painting.object_name
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getObject_name() {
        return object_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.object_name
     *
     * @param object_name the value for painting.object_name
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setObject_name(String object_name) {
        this.object_name = object_name == null ? null : object_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.status
     *
     * @return the value of painting.status
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.status
     *
     * @param status the value for painting.status
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.create_time
     *
     * @return the value of painting.create_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.create_time
     *
     * @param create_time the value for painting.create_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column painting.update_time
     *
     * @return the value of painting.update_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column painting.update_time
     *
     * @param update_time the value for painting.update_time
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}