package pwd.initializr.typeface.persistence.entity;

import java.util.ArrayList;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import pwd.initializr.typeface.persistence.dao.PaintingEntityMapper;

public class PaintingEntityExample {

    @Autowired
    PaintingEntityMapper mapper;

    public  void main(String[] args) {

    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public PaintingEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Long value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Long value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Long value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Long> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andFont_idIsNull() {
            addCriterion("font_id is null");
            return (Criteria) this;
        }

        public Criteria andFont_idIsNotNull() {
            addCriterion("font_id is not null");
            return (Criteria) this;
        }

        public Criteria andFont_idEqualTo(Long value) {
            addCriterion("font_id =", value, "font_id");
            return (Criteria) this;
        }

        public Criteria andFont_idNotEqualTo(Long value) {
            addCriterion("font_id <>", value, "font_id");
            return (Criteria) this;
        }

        public Criteria andFont_idGreaterThan(Long value) {
            addCriterion("font_id >", value, "font_id");
            return (Criteria) this;
        }

        public Criteria andFont_idGreaterThanOrEqualTo(Long value) {
            addCriterion("font_id >=", value, "font_id");
            return (Criteria) this;
        }

        public Criteria andFont_idLessThan(Long value) {
            addCriterion("font_id <", value, "font_id");
            return (Criteria) this;
        }

        public Criteria andFont_idLessThanOrEqualTo(Long value) {
            addCriterion("font_id <=", value, "font_id");
            return (Criteria) this;
        }

        public Criteria andFont_idIn(List<Long> values) {
            addCriterion("font_id in", values, "font_id");
            return (Criteria) this;
        }

        public Criteria andFont_idNotIn(List<Long> values) {
            addCriterion("font_id not in", values, "font_id");
            return (Criteria) this;
        }

        public Criteria andFont_idBetween(Long value1, Long value2) {
            addCriterion("font_id between", value1, value2, "font_id");
            return (Criteria) this;
        }

        public Criteria andFont_idNotBetween(Long value1, Long value2) {
            addCriterion("font_id not between", value1, value2, "font_id");
            return (Criteria) this;
        }

        public Criteria andFont_sizeIsNull() {
            addCriterion("font_size is null");
            return (Criteria) this;
        }

        public Criteria andFont_sizeIsNotNull() {
            addCriterion("font_size is not null");
            return (Criteria) this;
        }

        public Criteria andFont_sizeEqualTo(Float value) {
            addCriterion("font_size =", value, "font_size");
            return (Criteria) this;
        }

        public Criteria andFont_sizeNotEqualTo(Float value) {
            addCriterion("font_size <>", value, "font_size");
            return (Criteria) this;
        }

        public Criteria andFont_sizeGreaterThan(Float value) {
            addCriterion("font_size >", value, "font_size");
            return (Criteria) this;
        }

        public Criteria andFont_sizeGreaterThanOrEqualTo(Float value) {
            addCriterion("font_size >=", value, "font_size");
            return (Criteria) this;
        }

        public Criteria andFont_sizeLessThan(Float value) {
            addCriterion("font_size <", value, "font_size");
            return (Criteria) this;
        }

        public Criteria andFont_sizeLessThanOrEqualTo(Float value) {
            addCriterion("font_size <=", value, "font_size");
            return (Criteria) this;
        }

        public Criteria andFont_sizeIn(List<Float> values) {
            addCriterion("font_size in", values, "font_size");
            return (Criteria) this;
        }

        public Criteria andFont_sizeNotIn(List<Float> values) {
            addCriterion("font_size not in", values, "font_size");
            return (Criteria) this;
        }

        public Criteria andFont_sizeBetween(Float value1, Float value2) {
            addCriterion("font_size between", value1, value2, "font_size");
            return (Criteria) this;
        }

        public Criteria andFont_sizeNotBetween(Float value1, Float value2) {
            addCriterion("font_size not between", value1, value2, "font_size");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andBackgroundIsNull() {
            addCriterion("background is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundIsNotNull() {
            addCriterion("background is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundEqualTo(String value) {
            addCriterion("background =", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundNotEqualTo(String value) {
            addCriterion("background <>", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundGreaterThan(String value) {
            addCriterion("background >", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundGreaterThanOrEqualTo(String value) {
            addCriterion("background >=", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundLessThan(String value) {
            addCriterion("background <", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundLessThanOrEqualTo(String value) {
            addCriterion("background <=", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundLike(String value) {
            addCriterion("background like", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundNotLike(String value) {
            addCriterion("background not like", value, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundIn(List<String> values) {
            addCriterion("background in", values, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundNotIn(List<String> values) {
            addCriterion("background not in", values, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundBetween(String value1, String value2) {
            addCriterion("background between", value1, value2, "background");
            return (Criteria) this;
        }

        public Criteria andBackgroundNotBetween(String value1, String value2) {
            addCriterion("background not between", value1, value2, "background");
            return (Criteria) this;
        }

        public Criteria andForegroundIsNull() {
            addCriterion("foreground is null");
            return (Criteria) this;
        }

        public Criteria andForegroundIsNotNull() {
            addCriterion("foreground is not null");
            return (Criteria) this;
        }

        public Criteria andForegroundEqualTo(String value) {
            addCriterion("foreground =", value, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundNotEqualTo(String value) {
            addCriterion("foreground <>", value, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundGreaterThan(String value) {
            addCriterion("foreground >", value, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundGreaterThanOrEqualTo(String value) {
            addCriterion("foreground >=", value, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundLessThan(String value) {
            addCriterion("foreground <", value, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundLessThanOrEqualTo(String value) {
            addCriterion("foreground <=", value, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundLike(String value) {
            addCriterion("foreground like", value, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundNotLike(String value) {
            addCriterion("foreground not like", value, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundIn(List<String> values) {
            addCriterion("foreground in", values, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundNotIn(List<String> values) {
            addCriterion("foreground not in", values, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundBetween(String value1, String value2) {
            addCriterion("foreground between", value1, value2, "foreground");
            return (Criteria) this;
        }

        public Criteria andForegroundNotBetween(String value1, String value2) {
            addCriterion("foreground not between", value1, value2, "foreground");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Integer value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Integer value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Integer value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Integer value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Integer value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Integer> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Integer> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Integer value1, Integer value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Integer> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Integer> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andImage_urlIsNull() {
            addCriterion("image_url is null");
            return (Criteria) this;
        }

        public Criteria andImage_urlIsNotNull() {
            addCriterion("image_url is not null");
            return (Criteria) this;
        }

        public Criteria andImage_urlEqualTo(String value) {
            addCriterion("image_url =", value, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlNotEqualTo(String value) {
            addCriterion("image_url <>", value, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlGreaterThan(String value) {
            addCriterion("image_url >", value, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlGreaterThanOrEqualTo(String value) {
            addCriterion("image_url >=", value, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlLessThan(String value) {
            addCriterion("image_url <", value, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlLessThanOrEqualTo(String value) {
            addCriterion("image_url <=", value, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlLike(String value) {
            addCriterion("image_url like", value, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlNotLike(String value) {
            addCriterion("image_url not like", value, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlIn(List<String> values) {
            addCriterion("image_url in", values, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlNotIn(List<String> values) {
            addCriterion("image_url not in", values, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlBetween(String value1, String value2) {
            addCriterion("image_url between", value1, value2, "image_url");
            return (Criteria) this;
        }

        public Criteria andImage_urlNotBetween(String value1, String value2) {
            addCriterion("image_url not between", value1, value2, "image_url");
            return (Criteria) this;
        }

        public Criteria andBucket_nameIsNull() {
            addCriterion("bucket_name is null");
            return (Criteria) this;
        }

        public Criteria andBucket_nameIsNotNull() {
            addCriterion("bucket_name is not null");
            return (Criteria) this;
        }

        public Criteria andBucket_nameEqualTo(String value) {
            addCriterion("bucket_name =", value, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameNotEqualTo(String value) {
            addCriterion("bucket_name <>", value, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameGreaterThan(String value) {
            addCriterion("bucket_name >", value, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameGreaterThanOrEqualTo(String value) {
            addCriterion("bucket_name >=", value, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameLessThan(String value) {
            addCriterion("bucket_name <", value, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameLessThanOrEqualTo(String value) {
            addCriterion("bucket_name <=", value, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameLike(String value) {
            addCriterion("bucket_name like", value, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameNotLike(String value) {
            addCriterion("bucket_name not like", value, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameIn(List<String> values) {
            addCriterion("bucket_name in", values, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameNotIn(List<String> values) {
            addCriterion("bucket_name not in", values, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameBetween(String value1, String value2) {
            addCriterion("bucket_name between", value1, value2, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andBucket_nameNotBetween(String value1, String value2) {
            addCriterion("bucket_name not between", value1, value2, "bucket_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameIsNull() {
            addCriterion("object_name is null");
            return (Criteria) this;
        }

        public Criteria andObject_nameIsNotNull() {
            addCriterion("object_name is not null");
            return (Criteria) this;
        }

        public Criteria andObject_nameEqualTo(String value) {
            addCriterion("object_name =", value, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameNotEqualTo(String value) {
            addCriterion("object_name <>", value, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameGreaterThan(String value) {
            addCriterion("object_name >", value, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameGreaterThanOrEqualTo(String value) {
            addCriterion("object_name >=", value, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameLessThan(String value) {
            addCriterion("object_name <", value, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameLessThanOrEqualTo(String value) {
            addCriterion("object_name <=", value, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameLike(String value) {
            addCriterion("object_name like", value, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameNotLike(String value) {
            addCriterion("object_name not like", value, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameIn(List<String> values) {
            addCriterion("object_name in", values, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameNotIn(List<String> values) {
            addCriterion("object_name not in", values, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameBetween(String value1, String value2) {
            addCriterion("object_name between", value1, value2, "object_name");
            return (Criteria) this;
        }

        public Criteria andObject_nameNotBetween(String value1, String value2) {
            addCriterion("object_name not between", value1, value2, "object_name");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Long value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Long value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Long value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Long value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Long value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Long value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Long> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Long> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Long value1, Long value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Long value1, Long value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Long value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Long value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Long value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Long value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Long value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Long value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Long> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Long> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Long value1, Long value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Long value1, Long value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table painting
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 14 23:34:40 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table painting
     *
     * @mbggenerated Tue Apr 14 23:34:40 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}